# Generated by Django 4.1.3 on 2022-12-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usertoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="start_date",
            new_name="created_at",
        ),
    ]
