# Generated by Django 4.1.3 on 2022-12-03 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_start_date_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(2022, 12, 3, 11, 58, 16, 865687),
            ),
            preserve_default=False,
        ),
    ]
