# Generated by Django 4.1.3 on 2023-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_list_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="default_list_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
