# Generated by Django 4.1.3 on 2023-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_assigned_list_id_user_default_list_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="assigned_list_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="default_list_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
