# Generated by Django 4.1.3 on 2022-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repetitivetask",
            name="start_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repetitivetaskinfo",
            name="repetition",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
