# Generated by Django 4.1.3 on 2022-12-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_repetitivetask_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repetitivetaskinfo",
            name="super_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_tasks",
                to="tasks.repetitivetask",
            ),
        ),
    ]
