# Generated by Django 4.1.3 on 2022-12-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_repetitivetaskinfo_super_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repetitivetaskinfo",
            name="super_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_tasks",
                to="tasks.repetitivetaskinfo",
            ),
        ),
    ]
