# Generated by Django 4.1.3 on 2023-02-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_repetitivetaskinfo_super_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="super_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_tasks",
                to="tasks.task",
            ),
        ),
    ]
