# Generated by Django 4.1.3 on 2022-12-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_alter_membership_can_add_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="can_add_members",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="can_assign_tasks",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="can_edit_group",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Leader"), (2, "Member"), (3, "Guest")],
                default=2,
                null=True,
            ),
        ),
    ]
