# Generated by Django 4.1.3 on 2022-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_membership_can_add_members_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique member",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="members",
            new_name="users",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="member",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="unique member"
            ),
        ),
    ]
